### ISSUE TITLE
First event in Bologna

### ISSUE THREAD

**Issue by mcollina** [nodeschool/italy#1] opened 2014-12-10 13:44 UTC
The first event will be held in Bologna, if nobody else from somewhere else will help :).
The date is the 26th of February at [Working Capital Bologna]() and the registration link is https://www.eventbrite.com/e/nodeschool-bologna-tickets-15134524771.

We need help :) -- and also sponsors!

-------------------

Current mentors are:

* Matteo Collina @mcollina
* Marco Piraccini @marcopiraccini
* Michele Capra @piccoloaiutante
* Simone Busoli @simoneb
* Marco Montanari @sirmmo
* Matteo Murgida @teomurgi
* @MonsJovis
* Giuseppe Crinò @giuscri

---------------------

Which workshops are we going to do?

* learnyounode @piccoloaiutante @mcollina @giuscri @gpad
* expressworks - @teomurgi @simoneb @sirmmo
* stream-adventure - @mpiraccini
* going-native - @mcollina

-----------------------

(Updated to add mentors and and the details of the event)

**Comment by marcopiraccini** [comment] 2015-01-09 21:04
Ok, we agreed for the 26th of february 18-21 at WCAP, Bologna

**Comment by marcopiraccini** [comment] 2015-01-10 12:06
Here the eventbrite event: https://www.eventbrite.com/e/nodeschool-bologna-tickets-15134524771

**Comment by mcollina** [comment] 2015-01-13 09:46
Perfect, now we need to update the website and make some noise! :dancers:

I will do it tonight.

List of ML/groups to contact:

* [ ] @piccoloaiutante will add a link in the upcoming [nodejsconf.it](http://nodejsconf.it/) newsletter
* [ ] Bologna's PUG, XPUG, and maybe also our friends in the Romagna XPUG.
* [ ] Facebook groups 'Node.js Italy'

others?

**Comment by piccoloaiutante** [comment] 2015-01-13 16:23
@mcollina Ok but i don't know when we'll send the next mailing list since we're waiting to have the exact date for this year event. I guess next mail will be sent around the start to February, maybe it's a little bit late for Bologna's event.

**Comment by piccoloaiutante** [comment] 2015-01-13 16:26
We could also make some post on node.js conf it media channels..

**Comment by patiernom** [comment] 2015-01-14 11:48
@mcollina I will be there!!! 
+1 Bologna

**Comment by mcollina** [comment] 2015-01-14 12:08
@patiernom be sure to take friends/colleagues too! You can register here: https://www.eventbrite.com/e/nodeschool-bologna-tickets-15134524771

**Comment by marcopiraccini** [comment] 2015-01-19 08:49
Inscriptions are going good! Now we have an "happy problem": we need mentors... I've added a special "ticket" for mentors, so if someone of you has already the ticket and it's available to help as a mentor, please cancel the "partecipant" and then re-register with the "mentor" ticket.

**Comment by piccoloaiutante** [comment] 2015-01-19 08:50
@marcopiraccini count on me ;-)

**Comment by mcollina** [comment] 2015-01-19 09:03
@simoneb added himself as a mentor volunteer :D. I added you to the nodeschool/italy org :D.

Welcome Simone! :).

**Comment by simoneb** [comment] 2015-01-19 09:07
Thanks, looking forward to it!

**Comment by mcollina** [comment] 2015-01-19 10:57
it seems we are _already sold out_.

Current mentors are:

1. Matteo Collina (me)
2. Marco Piraccini @marcopiraccini 
3. Michele Capra @piccoloaiutante 
4. Simone Busoli @simoneb 
5. (Tentative) Matteo Murgida @teomurgi

**Comment by sirmmo** [comment] 2015-01-19 10:59
I'm available!!

**Comment by simoneb** [comment] 2015-01-19 11:01
@mcollina As far as mentors are involved, I presume. Any idea how many more seats are available otherwise? I'm planning to invite some people I know in the next few days but I'll hurry up if attendant's seats are running out too. BTW, at some point we may want to switch to Italian ;)

**Comment by mcollina** [comment] 2015-01-19 11:04
Not switching to Italian because other people in the nodeschool org _might_ want to join the discussion and help. Let's _aim_ to use English, and we'll see :).

Seats are _running out_. I think the room can handle up to 60 people, but we need more mentors to handle those.

**Comment by simoneb** [comment] 2015-01-19 11:07
@mcollina fair enough, considering that we can already handle the current subscriptions finding more mentors shoudn't be hard I guess

**Comment by MonsJovis** [comment] 2015-01-19 11:26
I'm available in case. I'm a friend of @sirmmo

**Comment by mcollina** [comment] 2015-01-19 13:37
I've opened up 5 more mentorship slots, and added the waitlist for the tickets.

**Comment by maccaluso** [comment] 2015-01-21 14:40
Hi everybody... just a quick presentation...
I'm Gianluca, I live and work in Bologna as Interaction Designer and frontend web developer. I'm not a real node expert (never used in production) but very curious about it. On the other side I'm a three.js enthusiast and Angular beginner/intermediate.
Another of my fields of interest is physical computing (e.g Arduino related stuff, especially the YUN which can run node servers).
I'll be glad if I can help in some way.

**Comment by MonsJovis** [comment] 2015-01-21 17:43
A quick presentation also of me...
I'm Markus, computer science student here in Bolgona but originally from South Tyrol. I'm a web developer since about 8 years and recently I used node for some projects and it was exciting. I think I could help as mentor for a beginner/intermediate approach.

**Comment by mcollina** [comment] 2015-01-21 18:36
@maccaluso I've added you to this org. Happy to get _any possible help_, we might need help with the basic workshoppers like 'learn you node', 'async you', and maybe express. We'll plan better who does what close to the event.

**Comment by simoneb** [comment] 2015-01-21 18:50
I candidate myself for the async stuff

**Comment by mcollina** [comment] 2015-01-21 18:51
Please go up and edit your issue and place your GH handle next to the workshop you would like to preparare.

**Comment by simoneb** [comment] 2015-01-21 22:52
@mcollina can't edit!

**Comment by giuscri** [comment] 2015-01-25 16:19
If your definition of mentor is someone who helps other people get their stuff done, helping them to clarify the key points for, say, asynchronous programming, promises, ... I would be **very** glad to help you as a mentor. :)

(I mean, I'm not ready to hold a *lesson* by myself on a topic of my choice!)

**Comment by mcollina** [comment] 2015-01-26 22:07
@giuscri from your profile I see you are based in Milan, would it be a problem to come to Bologna? We literally have zero budget. Anyway, we would like to see you as one of the organizers of #4!

**Comment by mcollina** [comment] 2015-01-26 22:08
@giuscri I've added you to the nodeschool Italy team!

**Comment by giuscri** [comment] 2015-01-26 22:30
@giuscri, course, I have no problem to come to Bologna!

**Comment by mcollina** [comment] 2015-01-26 22:32
@giuscri perfect, add yourself to the list of Mentors above!

**Comment by giuscri** [comment] 2015-01-26 22:58
@mcollina , are you sure I can do that? Apparently I have not enough permissions to edit the open post

**Comment by mcollina** [comment] 2015-01-27 07:48
@giuscri check your email, I have invited you to the nodeschool Italy team, and you have not accepted yet.

**Comment by giuscri** [comment] 2015-01-27 10:11
@mcollina, ops, I was expecting to be alerted *inside* github.com!

I've added myself as a mentor now. Ok :)

**Comment by teomurgi** [comment] 2015-01-27 10:44
@mcollina i'd like to give "expressjs", i cannot edit the original post

**Comment by marcopiraccini** [comment] 2015-02-04 12:49
In my opinion we have to cover as much as possible the "basic" workshops (since it's the first meeting).
At least stream-adventure and git-it (javascripting it's probably too basic) should be covered.
I candidate myself for both, but not at the same time :).  we need one mor mentor for "the other".

 Moreover in the basic table(s) I expect that we have to give instructions for installing node and git

**Comment by simoneb** [comment] 2015-02-04 13:23
@marcopiraccini not sure about git, if we're not enough to cover it I guess it should be just as well left behind, it doesn't have much to do with node after all

**Comment by marcopiraccini** [comment] 2015-02-08 15:49
Ok. Tomorrow morning I'm going to send an email asking how may people is interested for each workshop between the ones that we are willing to cover (see the post). Also I'm going to ask if someone is interested in one of the other workshops.

**Comment by simoneb** [comment] 2015-02-11 00:59
My bad for not realizing earlier that the workshops come from a fixed set with packages guiding you through the topic. I thought @mcollina came up with the names and the topics ;)

That's pretty cool indeed but I thought mentors had to prepare material, which is not the case. So I'm wondering, how are the workshops supposed to be held by mentors? Are there any guidelines or shall we simply show how to install and run the corresponding package and help people out when they're stuck?

**Comment by giuscri** [comment] 2015-02-11 11:30
> That's pretty cool indeed but I thought mentors had to prepare material, which is not the case. So I'm wondering, how are the workshops supposed to be held by mentors? Are there any guidelines or shall we simply show how to install and run the corresponding package and help people out when they're stuck?

From the mentor's perspective it sounds nice to prepare material to show but i would say that letting people to tinker with their own snippets is the best choice. Course, it depends on the level of the audience, but I suggest to simply helping them, really acting as **mentors**. Possibly at the end of the event they will have solved a minimum number of problems from a nodeschool module, and they'll be eager to finish it by themselves the next day.

Just my 2 satoshi.

**Comment by mcollina** [comment] 2015-02-11 19:54
Mentor sits there and fix people issues, explaining stuff and introducing the exercies, making sure everybody is on track and it is not stuck for too long. Loads of bad stuff can happen, especially for node newcomers.

**Comment by marcopiraccini** [comment] 2015-02-17 07:35
So far, the results of the poll is (23 participants answered):

ExpressWorks: 7
Learnyournode: 11
Going Native: 2
Async you: 1
Stream-adventure: 2

Also, 15 checked for the dinner.

**Comment by simoneb** [comment] 2015-02-17 07:42
Oh, so little love for async (I should have held it)! I guess that because
most people have seen little or nothing node before they don't see the need
for it, but they will eventually ;)

More seriously, I'm totally OK with cancelling the workshop if there's no
attendance.

**Comment by mcollina** [comment] 2015-02-17 08:07
Simone, you should do expressworks instead :).
Il giorno mar 17 feb 2015 alle 07:42 Simone Busoli notifications@github.com
ha scritto:

> Oh, so little love for async (I should have held it)! I guess that because
> most people have seen little or nothing node before they don't see the need
> for it, but they will eventually ;)
> 
> More seriously, I'm totally OK with cancelling the workshop if there's no
> attendance.

**Comment by marcopiraccini** [comment] 2015-02-17 08:13
I'm also surprised about Async (and Stream). Probably Simone, you  are right, most of the participants that answered know little about node. However, they are keeping answering. (+1 to Stream right now).

**Comment by simoneb** [comment] 2015-02-17 08:25
I don't mind doing any of the other workshops though, let's see how people
vote, there's still time.

**Comment by gpad** [comment] 2015-02-20 14:30
Hi to all, I'm available to help in nodeschool. I'd like to help you on this https://github.com/timoxley/functional-javascript-workshop but of course let me know how I can help.

**Comment by mcollina** [comment] 2015-02-20 17:44
@gpad that's great, there should be a ticket for you in https://www.eventbrite.com/e/nodeschool-bologna-tickets-15134524771 :).

**Comment by mcollina** [comment] 2015-02-20 17:45
Cool, it seems that the crowd is more aligned with expressworks and learn-you-node. If you want to prepare one of those and functional js, it would be awesome.

**Comment by gpad** [comment] 2015-02-20 18:08
@mcollina Ticket acquired!!! :+1: 
Just to be clear, are you talking about these [learn-you-node](https://github.com/rvagg/learnyounode) and these [expressworks](https://github.com/azat-co/expressworks)?

**Comment by mcollina** [comment] 2015-02-20 18:09
Yes.

Il giorno Fri Feb 20 2015 at 18:08:27 GPad notifications@github.com ha
scritto:

**Comment by marcopiraccini** [comment] 2015-02-20 18:36
Updated poll results (I think that we consider this final):

ExpressWorks: 7
Learnyournode: 14
Going Native: 2
Async you: 1
Stream-adventure: 4

Pizza: 17

**Comment by mcollina** [comment] 2015-02-20 18:55
Let's think about the pizza. Where are we going?
Il giorno ven 20 feb 2015 alle 18:36 Marco notifications@github.com ha
scritto:

**Comment by marcopiraccini** [comment] 2015-02-21 09:21
Scalinatella (http://www.ristorantepizzeriascalinatella.it/) is near. I've never been there but a friend of mine says it's good. I will call and ask if they can arrange for (at least) 20.

**Comment by mcollina** [comment] 2015-02-21 10:28
Ok for me.
Il giorno sab 21 feb 2015 alle 10:21 Marco notifications@github.com ha
scritto:

**Comment by gpad** [comment] 2015-02-21 10:30
:+1:

**Comment by giuscri** [comment] 2015-02-22 16:12
i'm glad to help for the `learn-you-node` workshop mainly.
For the pizza, i'm pretty sure i have to dismiss since i will take the train back to Milan at 10pm.

as far as i'm seeing, the location (via Oberdan) seems close to the station (~10 minutes by walk). am i right?

**Comment by marcopiraccini** [comment] 2015-02-22 16:18
Yes, approx 10 min (take 15 just to be sure).

**Comment by marcopiraccini** [comment] 2015-02-23 07:44
Today I'm going to make the reservation of the restaurant for 25 (17 confirmed with the poll + 8 mentors). 
I'll probably switch to Nicola's ( http://bit.ly/1a2NjxH ) because it's really near (it's in front of the WCAP).

**Comment by mcollina** [comment] 2015-02-23 07:47
That's perfect. What about timing? 21:15 is ok?

**Comment by marcopiraccini** [comment] 2015-02-23 07:57
Yes, about 21:15 should be ok.

**Comment by simoneb** [comment] 2015-02-23 08:42
Don't count me in, I might have to leave right after the meeting.

**Comment by mcollina** [comment] 2015-02-23 17:22
Given the answers in the pools, I rearranged the workshop we are going to do as the following:
- learnyounode @piccoloaiutante @mcollina @giuscri @gpad
- expressworks - @teomurgi @simoneb
- stream-adventure - @mpiraccini
- going-native - @mcollina

I still need an answer from: @sirmmo @gpad @maccaluso. What workshop would you like to do? Ideally either learnyounode or expressworks. Let me know.

I am signing up myself for both going native and learnyounode, if I am needed there too.

**Comment by gpad** [comment] 2015-02-23 18:23
For me is ok learnyounode and expressworks, I'll do what is required!!!

**Comment by marcopiraccini** [comment] 2015-02-23 21:11
About pizza: reserved for 24 (more or less) at Nicola's at about 21:15

**Comment by marcopiraccini** [comment] 2015-02-25 00:17
I've prepared a very small presentation (6 -7 slides) just as introduction for the first 5-10 minutes. 
Then we will split. Probably it's a good idea to use the projector for the "learyournode" guys (which are at least 14). At least to show them how to launch node, npm, etc. (I also expect that they have to install node).

**Comment by mcollina** [comment] 2015-02-25 08:41
Anybody develops on Windows? I expect to see some Windows devs there, so we might want to support those in the cleanest possible way.

For everybody, let's try to meet there at 17:30-17:45, so we can set up ourselves before the event.

**Comment by piccoloaiutante** [comment] 2015-02-25 09:43
I've setup node on windows so I could support windows people ;-)

**Comment by mcollina** [comment] 2015-02-25 10:25
awesome!

**Comment by giuscri** [comment] 2015-02-25 10:48
> For everybody, let's try to meet there at 17:30-17:45, so we can set up ourselves before the event.

ok! :)

**Comment by marcopiraccini** [comment] 2015-02-25 10:51
Perfect. I should be there at about 17:15

**Comment by patiernom** [comment] 2015-02-25 11:07
I have node installed on a Windows machine too, so if needed I can give a hand to all Windows users

**Comment by gpad** [comment] 2015-02-25 13:10
I should be there around 17.30 see you tomorrow :-)

**Comment by maccaluso** [comment] 2015-02-25 16:56
Hey guys...
I'm really sorry (and definitely on late - I know) but I'm under a deadline and I can't participate at the event.
Anyway I'd like to wish everybody a good json for tomorrow.

Have fun.

Gianluca Macaluso

I dati personali contenuti in questa comunicazione e nei relativi allegati, devono essere considerati riservati e confidenziali. Qualora non siate il destinatario siete pregati di contattare il mittente della presente e siete diffidati dall'utilizzare ogni dato personale contenuto. L'eventuale utilizzo è sanzionato dall'art. 2043 c.c. e dall'art. 167 d.lg. 196/03.

**Comment by vforvalerio87** [comment] 2015-02-25 18:33
I see on Eventbrite that a spot has opened up, but when I try to register I get a message telling me it's too late to register. Can I still attend?

**Comment by marcopiraccini** [comment] 2015-02-25 20:53
Yes. Valerio, try now.

**Comment by rjack** [comment] 2015-02-25 21:12
Hi everyone, is every spot taken or is it possible to join as attendee?

**Comment by mcollina** [comment] 2015-02-26 10:58
@rjack unfortunately we are tight on the amount of people we can let in, and we have a sharp limit of 50 attendees (including mentors). The waitlist is so long, so we cannot make exceptions :(.

**Comment by patiernom** [comment] 2015-02-26 12:07
There are problems if I participate in "going-native" workshop instead "expressworks" ????

**Comment by marcopiraccini** [comment] 2015-02-26 12:08
Of course, not :)
The poll was only indicative.

**Comment by rjack** [comment] 2015-02-26 12:16
@mcollina no problem, hopefully I'll join future dates. How can I keep updated on events of the Bologna node community?

**Comment by mcollina** [comment] 2015-02-26 14:20
Watch this repo as for now, you will get notified for all dates around
Italy, which is not that bad. If Bologna becomes a recurring event we will
spawn a separate repo :)
Il giorno gio 26 feb 2015 alle 13:16 Giacomo Ritucci <
notifications@github.com> ha scritto:

**Comment by simoneb** [comment] 2015-02-26 22:30
Considering that my train back home had 1+ hour delay I could have just as well joined you for the pizza!
Nevertheless, thanks to all who attended (including the mentors) for the nice evening and I hope the attendees enjoyed the experience.

I propose to close this issue ;)

**Comment by piccoloaiutante** [comment] 2015-02-27 08:39
Well done guys! It was a blast yesterday :-)

**Comment by marcopiraccini** [comment] 2015-02-28 09:42
Ok, I think that we can close this issue

**Closed by marcopiraccini** 2015-02-28 09:42 UTC

**Comment by mcollina** [comment] 2015-02-28 09:46
Great work folks!!
