### ISSUE TITLE
Milan

### ISSUE THREAD

**Issue by piccoloaiutante** [nodeschool/italy#4] opened 2014-12-18 11:44 UTC
Hi,

i thought about hosting an event in Talent Garden in Brescia but i think that having it in Milano could have more impact.

Is there anyone else that want to join the forces? :-)

**Comment by piccoloaiutante** [comment] 2015-01-19 09:12
Given the number of people that are going to participate in Bologna what do you think to choose a date for the Milan event and announcing it in Bologna?

**Comment by piccoloaiutante** [comment] 2015-01-19 09:13
maybe @gabrielelana could be interested to participate as mentor..

**Comment by teomurgi** [comment] 2015-01-21 11:21
I'm getting information about a 65mq room in a  coworking space in Milano, free (coffee and projector excluded)

**Comment by piccoloaiutante** [comment] 2015-01-21 11:52
I'm getting info too from Talent garden Milan. I'll keep you posted ;-)

**Comment by foysalit** [comment] 2015-01-22 14:28
I'm from Turin and there so Milan is quite close to the city and I would love to attend. subscribing to the thread to keep track :+1:

**Comment by gabrielelana** [comment] 2015-01-23 06:04
@piccoloaiutante let's talk about it, send me an email

**Comment by Granze** [comment] 2015-02-26 10:47
Hey @piccoloaiutante , we (Milano JS) will be happy to help you with the organization part. Let me know.

**Comment by piccoloaiutante** [comment] 2015-02-26 11:03
Hi @Granze, good to hear that. It will be in the second part of may. Now we're focusing on where to host it. Do you have any suggestion?

**Comment by Granze** [comment] 2015-02-26 11:12
Maybe you can ask to Google Italia, they have a brand new office in Milan. Another option could be Copernico, but I've never been there so I don't know how it is.

**Comment by piccoloaiutante** [comment] 2015-02-26 11:14
ok i'll contact @rainbowbreeze to see if we can get there, thx

**Comment by mcollina** [comment] 2015-03-03 21:16
I would like Milan to be in for http://nodeschool.io/international-day/.

**Comment by marcopiraccini** [comment] 2015-03-05 19:26
Yes, why not? :)

**Comment by mcollina** [comment] 2015-03-07 13:57
We still need the location. @piccoloaiutante start stalking @rainbowbreeze.

**Comment by simoneb** [comment] 2015-03-08 12:28
There's a WCAP in Milan, I don't know them but it might be an option too

**Comment by mcollina** [comment] 2015-03-08 12:34
WCAP does not host on Saturdays, which is our target for the International
Day, if we want to be in.

Il giorno dom 8 mar 2015 alle ore 13:28 Simone Busoli <
notifications@github.com> ha scritto:

**Comment by simoneb** [comment] 2015-03-08 12:39
Good point, I guess it might not be easy to find a location, I assume
companies might not be in for opening their spaces on Saturdays either. In
case it turns out to be too difficult to find a location I would also
consider moving it to Friday, a relatively minor change ;)

**Comment by piccoloaiutante** [comment] 2015-03-08 13:54
@mcollina i'm sending an email to @rainbowbreeze right now ;-)

**Comment by mcollina** [comment] 2015-03-18 07:34
hey @kildem, we were discussing here about doing the International Day in Milan, but we have trouble finding the location.

**Comment by bajtos** [comment] 2015-03-23 17:50
Perhaps the people running Milan MEAN group can help? http://www.meetup.com/MM-MeanMilan/ and http://www.copernicomilano.it/

**Comment by mcollina** [comment] 2015-03-23 23:17
We are already talking with them! Hopefully we'll be able to get a venue
for running the International Day!
Il giorno lun 23 mar 2015 alle 18:50 Miroslav Bajtoš <
notifications@github.com> ha scritto:

**Comment by lambrojos** [comment] 2015-03-30 08:16
Hi, Giovanni from LinkMe/MeanMilan here.. I think I could help as a mentor if needed, I feel comfortable with the basic workshoppers plus promises, async. functional javascript and express.. maybe also count to 6 but the workshopper looks a bit incomplete. @teone could also help? 

About the location, I was chatting with my colleague Sara (MeanMilan community manager), she is absolutely sure that she can find sponsors to cover costs at copernico..could this be a solution?

**Comment by mcollina** [comment] 2015-03-30 08:21
Copernico is good. We would love to be part of the International Day, which is the 23rd of May (Saturday).

We would need wifi for everybody. Copernico is a good location, you did your talk there @bajtos? Is it a good venue for a nodeschool event?

**Comment by bajtos** [comment] 2015-03-30 10:08
> Copernico is a good location, you did your talk there @bajtos? Is it a good venue for a nodeschool event?

I think's it's okay. It all depends on the number of people that you expect to attend and whether there will be enough seats for that number. For my workshop, we had about 20-30 attendees (please correct me @lambrojos if I am wrong) and the place served us very well.

**Comment by mcollina** [comment] 2015-03-30 10:12
Do you think it can accomodate 50 people? That's our target size, based on
Bologna experience!
Il giorno lun 30 mar 2015 alle 12:08 Miroslav Bajtoš <
notifications@github.com> ha scritto:

**Comment by bajtos** [comment] 2015-03-30 10:14
> Do you think it can accomodate 50 people? That's our target size, based on
> Bologna experience!

I can't answer that, perhaps @lambrojos or Sara can check with Copernico?

**Comment by teone** [comment] 2015-03-30 13:23
Hi everybody, I could also help as mentor, as @lambrojos said for:

> I feel comfortable with the basic workshoppers plus promises, async. functional javascript and express.. maybe also count to 6 but the workshopper looks a bit incomplete.

I think that copernico can accomodato 50 people, but this only my opinion, I'll ask Sara to check with them directly.

**Comment by lambrojos** [comment] 2015-03-30 14:38
Ok just checked with Copernico, they said we have two choices:
- plenary room with 70 seats with flip up desks and no tables - I think that's a dealbreaker.
- another room inside the coworking (not the one we used with @bajtos) , with tables, and ~50 seats - Marina from copernico says this room  can accomodate up to 60 people, but they will be packed like sardines

Both solutions include wifi and projector screen

I think the second solution might work.. thoughts?

**Comment by marcopiraccini** [comment] 2015-03-30 14:39
+1 for the "tables" solution

**Comment by kildem** [comment] 2015-04-04 16:20
(International Day) What about a venue near airport Milano(Bergamo)? Could it be possible?

**Comment by marcopiraccini** [comment] 2015-04-21 16:04
So, it's fixed for the 23th of May?

**Comment by teone** [comment] 2015-04-23 07:13
@marcopiraccini Yes, as I know it's confirmed.

**Comment by kildem** [comment] 2015-04-28 17:08
@marcopiraccini do you have some powerpoint presentation to leave to those who want to introduce a nodeschool event? If you have, how can I contact you?

**Comment by piccoloaiutante** [comment] 2015-04-29 07:34
I can say that we found location and sponsor. More news to come this week :)

**Comment by marcopiraccini** [comment] 2015-04-29 08:17
Great!

**Comment by mcollina** [comment] 2015-05-07 13:55
Would we like to do stickers https://github.com/nodeschool/international-day/issues/7?

**Comment by mcollina** [comment] 2015-05-07 13:55
Or should we use the NodeSchool Italy ones?

**Comment by piccoloaiutante** [comment] 2015-05-07 13:58
Well, we still have about 50 stickers of the italian version. We could print also for the international day, the cost will be approximately the same as the last time.

**Comment by piccoloaiutante** [comment] 2015-05-07 14:05
The event is out https://www.eventbrite.it/e/biglietti-nodeschool-italy-milano-16784771704

**Comment by simoneb** [comment] 2015-05-07 14:07
We've got some left from yesterday's event, too.

**Comment by marcopiraccini** [comment] 2015-05-07 17:29
Updated the web page.

**Comment by lambrojos** [comment] 2015-05-15 08:29
As the date is closing in, I think  it's time to decide which workshoppers we are going to use!
A little survey was run on eventbrite and as now only 12 people answered :

![here are the results](https://cloud.githubusercontent.com/assets/1526036/7649247/7874c300-faeb-11e4-9052-148ce29d88d0.png)

I don't know it this sample is significative, but I am quite surprised that the winner is javascripting.

As it looks like that we have some total newbies my proposals are:
- javascripting 
- learnyoude
- expressworks
- promise it won't hurt

If @mcollina wants to torture some poor soul with Going native he is more than welcome :)

Any more ideas?

Then I would also like to understand who is going in to mentor, as far as I know the mentors are: 
- me 
- @teone 
- @mcollina (90% sure)
- ?

**Comment by marcopiraccini** [comment] 2015-05-15 09:13
Count on me as mentor

**Comment by piccoloaiutante** [comment] 2015-05-15 09:14
I'll be there as mentor too :-)

**Comment by teone** [comment] 2015-05-15 10:13
I'll be there and I'm ok with @lambrojos proposal for workshop topic.

**Comment by simoneb** [comment] 2015-05-15 11:35
How many people are attending? If there's a need for mentors I can join as well.

**Comment by teone** [comment] 2015-05-15 14:30
The limit is set to 50 people. As now there 3 tickets left.

If you would like to Join you're welcome! I don't see any problem in increasing the mentor's number!

**Comment by lambrojos** [comment] 2015-05-15 14:38
Yes, this time the more mentors, the better :)

any toughts about the workshoppers ?

**Comment by simoneb** [comment] 2015-05-15 14:45
> any toughts about the workshoppers ?

@lambrojos actually yes, I'd had an idea of writing our own, Italian-based bonus workshop, which would be funny, but once I've looked at the code of even simple exercises of learnyounode I dropped the idea, it's way too much work! So I'm fine with whatever candidates choose :)

**Comment by piccoloaiutante** [comment] 2015-05-20 09:11
Is there any other mentor that would like to join us? We are currently five people :-)

**Comment by simoneb** [comment] 2015-05-20 09:12
I'm in!

**Comment by piccoloaiutante** [comment] 2015-05-20 09:13
awesome :)

**Comment by piccoloaiutante** [comment] 2015-05-22 15:12
So see you tomorrow guys!

**Comment by teone** [comment] 2015-05-22 19:41
Yeah! You'll find us there from 2 pm

**Closed** 2015-06-04 15:44 UTC
